language: perl

perl:
  - "5.28"
  #- "5.26"
  #- "5.24"
  #- "5.22"
  #- "5.20"
  - "5.16"

addons:
  apt:
    packages:
      # From Zonemaster Engine installation instruction
    - autoconf
    - automake
    - build-essential
    - cpanminus
    - libclone-perl
    - libdevel-checklib-perl
    - libfile-sharedir-perl
    - libfile-slurp-perl
    - libidn11-dev
    - libintl-perl
    - libio-socket-inet6-perl
    - libjson-pp-perl
    - liblist-moreutils-perl
    - liblocale-msgfmt-perl
    - libmail-rfc822-address-perl
    - libmodule-find-perl
    - libmoose-perl
    - libnet-ip-perl
    - libpod-coverage-perl
    - libreadonly-xs-perl
    - libssl-dev
    - libtest-differences-perl
    - libtest-exception-perl
    - libtest-fatal-perl
    - libtest-pod-perl
    - libtext-csv-perl
    - libtool
    - m4
      # From Zonemaster CLI installation instruction
    - libmoosex-getopt-perl
    - libtext-reflow-perl

before_install:
  # Help Perl find modules installed from OS packages
- export PERL5LIB=/usr/share/perl5

  # Provide cpanm helper
- eval $(curl https://travis-perl.github.io/init) --auto

  # Zonemaster LDNS needs a newer version of Module::Install
- cpan-install Module::Install Module::Install::XSUtil

  # Install Zonemaster LDNS
- git clone --depth=1 --branch=51-ed25519 https://github.com/mattias-p/zonemaster-ldns.git
- ( cd zonemaster-ldns && cpanm --verbose --notest --configure-args="--no-ed25519" . ) && rm -rf zonemaster-ldns

  # Install Zonemaster Engine
- git clone --depth=1 --branch=$TRAVIS_BRANCH https://github.com/zonemaster/zonemaster-engine.git
- ( cd zonemaster-engine && cpanm --verbose --notest . ) && rm -rf zonemaster-engine

before_script:
  # Run tests in the clone directory
- pwd ; cd $TRAVIS_BUILD_DIR ; pwd
- rm -rf build_dir

script:
- perl Makefile.PL
- make --trace test
