language: perl
perl:
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.16"
before_install:
    - eval $(curl https://travis-perl.github.io/init) --auto
    - local-lib
    - git clone --depth=1 --branch=develop https://github.com/zonemaster/zonemaster-ldns.git
    - git clone --depth=1 --branch=develop https://github.com/zonemaster/zonemaster-engine.git
    - cpan-install --deps Devel::CheckLib Module::Install Module::Install::XSUtil ./zonemaster-ldns ./zonemaster-engine
